Document: dxf2gcode
Title: Debian dxf2gcode Manual
Author: <insert document author here>
Abstract: This manual describes what dxf2gcode is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dxf2gcode/dxf2gcode.sgml.gz

Format: postscript
Files: /usr/share/doc/dxf2gcode/dxf2gcode.ps.gz

Format: text
Files: /usr/share/doc/dxf2gcode/dxf2gcode.text.gz

Format: HTML
Index: /usr/share/doc/dxf2gcode/html/index.html
Files: /usr/share/doc/dxf2gcode/html/*.html
